Repository Legendary2/GB_CommandProgCPP_team3, pull requests merged in 2023-03, with the labels that each got.

#91 P_R2T12[Dev] Разработаны функции `Bold` и `Italic`
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  README.MD
Labels: Требуется слияние, Готово

#92 P_R2Dev Слияние второго релиза
  .gitignore
  EditorTeam/CMakeLists.txt
  EditorTeam/EditorTeam.pro
  EditorTeam/const_strings.h
  EditorTeam/filehandler.cpp
  EditorTeam/filehandler.h
  EditorTeam/helpbrowser.cpp
  EditorTeam/helpbrowser.h
  EditorTeam/idevhandler.h
  EditorTeam/main.cpp
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/resources/images/align_center.png
  EditorTeam/resources/images/align_left.png
  EditorTeam/resources/images/align_right.png
  EditorTeam/resources/images/app_icon.png
  EditorTeam/resources/images/bold.png
  EditorTeam/resources/images/close.png
  EditorTeam/resources/images/copy.png
  EditorTeam/resources/images/copy_format.png
  EditorTeam/resources/images/crossed.png
  EditorTeam/resources/images/cut.png
  EditorTeam/resources/images/exit.png
  EditorTeam/resources/images/font.png
  EditorTeam/resources/images/help.png
  EditorTeam/resources/images/icon_128.png
  EditorTeam/resources/images/icon_256.png
  EditorTeam/resources/images/icon_32.png
  EditorTeam/resources/images/icon_64.png
  EditorTeam/resources/images/italic.png
  EditorTeam/resources/images/keybinds.png
  EditorTeam/resources/images/language.png
  EditorTeam/resources/images/new.png
  EditorTeam/resources/images/open.png
  EditorTeam/resources/images/paste.png
  EditorTeam/resources/images/paste_format.png
  EditorTeam/resources/images/print.png
  EditorTeam/resources/images/save.png
  EditorTeam/resources/images/save_as.png
  EditorTeam/resources/images/select_all.png
  EditorTeam/resources/images/style.png
  EditorTeam/resources/images/tedit.png
  EditorTeam/resources/images/underline.png
  EditorTeam/resources/resources.qrc
  EditorTeam/resources/translation/l10n_en.qm
  EditorTeam/resources/translation/l10n_ru.qm
  README.MD
Labels: Готово

#99 P_R3B1[Bug] Разработана getCurrentCharFormat()
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  README.MD
Labels: Требуется слияние

#95 P_R1T8[Dev] Реализация функции About
  EditorTeam/mainwindow.cpp
  EditorTeam/resources/helpfiles/about.htm
  EditorTeam/resources/helpfiles/edit.htm
  EditorTeam/resources/helpfiles/files.htm
  EditorTeam/resources/helpfiles/index.htm
  EditorTeam/resources/helpfiles/setting.htm
  EditorTeam/resources/helpfiles/style.css
  EditorTeam/resources/resources.qrc
Labels: Требуется слияние

#93 P_R3T8[Dev]Разработка диалогового окна Settings
  EditorTeam/CMakeLists.txt
  EditorTeam/const_strings.h
  EditorTeam/helpbrowser.cpp
  EditorTeam/helpbrowser.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/resources/images/cancel.png
  EditorTeam/resources/images/grey_style.png
  EditorTeam/resources/images/language.png
  EditorTeam/resources/images/ok.png
  EditorTeam/resources/images/russia.png
  EditorTeam/resources/images/settings.png
  EditorTeam/resources/images/style.png
  EditorTeam/resources/images/usa.png
  EditorTeam/resources/images/white_style.png
  EditorTeam/resources/resources.qrc
  EditorTeam/settingskeeper.cpp
  EditorTeam/settingskeeper.h
Labels: Требуется слияние

#106 P_R3B1[Bug] Рефакторинг getCurrentCharFormat().
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  README.MD
Labels: Требуется слияние

#111 P_R3B4[Bug] Баг в функции Bold
  EditorTeam/mainwindow.cpp
Labels: Требуется слияние

#112 P_R3B3[Bug] Баг в функции Italic
  EditorTeam/mainwindow.cpp
Labels: Требуется слияние

#113 P_R3B7[Bug] Баг в функции Fonts
  EditorTeam/mainwindow.cpp
Labels: Требуется слияние

#110 P_R3B6[Bug] Баг в функции `Underlined`
  EditorTeam/mainwindow.cpp
Labels: Требуется слияние

#120 P_R3T1[Dev]Разработка функции `Search through text` #49
  EditorTeam/CMakeLists.txt
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/resources/images/search.png
  EditorTeam/resources/resources.qrc
  EditorTeam/searchform.cpp
  EditorTeam/searchform.h
  EditorTeam/searchhighlight.cpp
  EditorTeam/searchhighlight.h
Labels: Требуется слияние

#117 P_R3T5[Dev] Разработка функции `Text colour`
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/resources/images/text_color.png
  EditorTeam/resources/resources.qrc
Labels: Требуется слияние

#121 P_R3_T2[Dev] Разработка функции `Open for read` #50
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/resources/helpfiles/files.htm
  EditorTeam/resources/images/open_read_only.png
  EditorTeam/resources/images/save_to_pdf.png
  EditorTeam/resources/resources.qrc
Labels: Требуется исправление

#96 P_R2T15[Dev]Разработка функции `ToolBar`
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
Labels: Требуется слияние

#125 P_R3T9[Dev] Имплементация собственного расширения для работы ПО #59
  .gitignore
  EditorTeam/CMakeLists.txt
  EditorTeam/arch/7za.dll
  EditorTeam/arch/7za.exe
  EditorTeam/arch/7zzs
  EditorTeam/filehandler.cpp
  EditorTeam/filehandler.h
  EditorTeam/helpbrowser.cpp
  EditorTeam/helpbrowser.h
  EditorTeam/idevhandler.h
  EditorTeam/mainwindow.cpp
  EditorTeam/settingskeeper.cpp
  EditorTeam/settingskeeper.h
Labels: Требуется слияние
