Repository Legendary2/GB_CommandProgCPP_team3, pull requests merged in 2023-02, with the labels that each got.

#13 Разработан макет для первого релиза
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
Labels: Слияние

#14 В главное меню добавлен элемент New
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
Labels: Требуется слияние

#28 Добавил реализацию функций Exit и Close
  EditorTeam/EditorTeam.pro
  EditorTeam/EditorTeam.pro.user
  EditorTeam/main.cpp
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/mainwindow.ui
  LICENSE
  README.MD
Labels: Требуется проверка

#30 Требуется слияние с веткой develop
  EditorTeam/EditorTeam.pro
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/resources/resources.qrc
  EditorTeam/resources/themes/grey.qss
  EditorTeam/resources/themes/white.qss
  README.MD
Labels: Слияние

#32 Добавил реализацию функций New и Open
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/mainwindow.ui
  README.MD
Labels: Требуется проверка

#37 Gubaydullin RG
  EditorTeam/main.cpp
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/mainwindow.ui
Labels: Слияние

#38 Lyashenko an
  EditorTeam/EditorTeam.pro
  EditorTeam/EditorTeam.pro.user
  EditorTeam/helpbrowser.cpp
  EditorTeam/helpbrowser.h
  EditorTeam/helpbrowser.ui
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/mainwindow.ui
  EditorTeam/resources/helpfiles/index.htm
  EditorTeam/resources/images/about.png
  EditorTeam/resources/images/tedit.png
  EditorTeam/resources/resources.qrc
Labels: Слияние

#39 Добавление функции мультиязычности
  .gitattributes
  .gitignore
  EditorTeam/.gitignore
  EditorTeam/EditorTeam.pro
  EditorTeam/EditorTeam.pro.user
  EditorTeam/const_strings.h
  EditorTeam/helpbrowser.ui
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/mainwindow.ui
  EditorTeam/resources/resources.qrc
  EditorTeam/resources/translation/l10n_en.qm
  EditorTeam/resources/translation/l10n_en.ts
  EditorTeam/resources/translation/l10n_ru.qm
  EditorTeam/resources/translation/l10n_ru.ts
  LICENSE
Labels: Слияние

#71 P_R2T8[Dev] Переход проекта на CMake
  .gitignore
  EditorTeam/CMakeLists.txt
  EditorTeam/EditorTeam.pro
  EditorTeam/helpbrowser.cpp
  EditorTeam/helpbrowser.h
  EditorTeam/resources/translation/l10n_en.qm
  EditorTeam/resources/translation/l10n_ru.qm
Labels: Требуется слияние

#69 P_R2T10[Dev] Разработка модуля файлов
  EditorTeam/CMakeLists.txt
  EditorTeam/const_strings.h
  EditorTeam/filehandler.cpp
  EditorTeam/filehandler.h
  EditorTeam/helpbrowser.h
  EditorTeam/idevhandler.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
Labels: Требуется слияние

#77 P_R2T6[DEV] Разработка функции Fonts 46
  EditorTeam/mainwindow.cpp
Labels: Слияние

#68 P_R2T5[Dev] Добавлена реализация функции Align text center
  EditorTeam/mainwindow.cpp
  README.MD
Labels: Требуется слияние

#75 P_R2T1[DEV] Добавил функцию `Print`
  EditorTeam/CMakeLists.txt
  EditorTeam/mainwindow.cpp
Labels: Требуется слияние

#79 P_R2T4[DEV] Функция `Align text right`
  EditorTeam/mainwindow.cpp
Labels: Требуется слияние

#72 P_R2T3_44[Dev] Добавление функции `Align text left`
  EditorTeam/mainwindow.cpp
Labels: Требуется слияние

#83 R2T14_64[Dev] Реализовал функцию `Crossed` согласно ТТ
  .gitignore
  EditorTeam/CMakeLists.txt
  EditorTeam/EditorTeam.pro
  EditorTeam/const_strings.h
  EditorTeam/filehandler.cpp
  EditorTeam/filehandler.h
  EditorTeam/helpbrowser.cpp
  EditorTeam/helpbrowser.h
  EditorTeam/idevhandler.h
  EditorTeam/main.cpp
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/resources/images/align_center.png
  EditorTeam/resources/images/align_left.png
  EditorTeam/resources/images/align_right.png
  EditorTeam/resources/images/app_icon.png
  EditorTeam/resources/images/close.png
  EditorTeam/resources/images/copy_format.png
  EditorTeam/resources/images/exit.png
  EditorTeam/resources/images/font.png
  EditorTeam/resources/images/help.png
  EditorTeam/resources/images/icon_128.png
  EditorTeam/resources/images/icon_256.png
  EditorTeam/resources/images/icon_32.png
  EditorTeam/resources/images/icon_64.png
  EditorTeam/resources/images/keybinds.png
  EditorTeam/resources/images/language.png
  EditorTeam/resources/images/new.png
  EditorTeam/resources/images/open.png
  EditorTeam/resources/images/paste_format.png
  EditorTeam/resources/images/print.png
  EditorTeam/resources/images/save.png
  EditorTeam/resources/images/save_as.png
  EditorTeam/resources/images/style.png
  EditorTeam/resources/images/tedit.png
  EditorTeam/resources/resources.qrc
  EditorTeam/resources/translation/l10n_en.qm
  EditorTeam/resources/translation/l10n_ru.qm
  README.MD
Labels: Требуется проверка

#81 P_R2T13[Dev]Разработка функции `Underlined`
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
Labels: Требуется слияние

#85 P_R2D1[Doc] Дополнительные иконки (для формата шрифта)
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/resources/images/bold.png
  EditorTeam/resources/images/crossed.png
  EditorTeam/resources/images/italic.png
  EditorTeam/resources/images/underline.png
  EditorTeam/resources/resources.qrc
Labels: Требуется проверка

#80 P_R2T16[Dev] Разработана функция `Размер шрифта`
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
Labels: Требуется проверка

#86 P_R2T7[Dev] Разработана функция `Key bindings`
  EditorTeam/mainwindow.cpp
Labels: Слияние

#87 P_R2T18[Dev] Разработка контекстного меню
  EditorTeam/const_strings.h
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
  EditorTeam/resources/images/copy.png
  EditorTeam/resources/images/cut.png
  EditorTeam/resources/images/paste.png
  EditorTeam/resources/images/select_all.png
  EditorTeam/resources/resources.qrc
Labels: Готово

#78 P_R2T17[DEV] Реализация задачи `Apply text format`
  EditorTeam/mainwindow.cpp
  EditorTeam/mainwindow.h
Labels: Требуется проверка
